services:
  api:
    build: .
    container_name: patudos-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO:-update}
      SHOW_SQL: ${SHOW_SQL:-false}