spring.application.name=ESTUDO_PATUDOS_API_SPRING_JPA

# H2 Console - Para você ver o banco no navegador
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:patudosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Faz o Spring mostrar no console o SQL que ele está gerando (Ótimo para aprender!)
spring.jpa.show-sql=true